# -*- coding: utf-8 -*-
"""String28Jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmdN3vFKN7D7P_x7GK65UACJq37pSGOo
"""

#String
word='codetechniq'
print(word[5:-2])

word='codetechniq'
print(word[0:5])

a='Pankaj'
print(a[0],a[1],a[2],a[3],a[4],a[5 ])

a,b='Pankaj','Chauhan'
print(a,b)

a='Pankaj'
b='Chauhan'
print('a+b=',a+b)
print('a*3=',a*3)
print('b*3=',b*3)
print('a*3+b*3',a*3,b*3)

a=input('Enter the name ')
for i in range(len(a)):
 print('Character at Index '+str(i)+' is '+a[i])

a = 'Pankaj'
print('1st = ', a)
print('2nd = ', a[0])
print('3rd = ',a[-1])
print('4th = ',a[0:3])
print('5th = ',a[3:-2])

a='PANKAJ'
b='pankaj'
print(a.lower())
print(b.upper())

a='00000000000Pankaj Chauhan000000000000000000000011116666644444'
print(a.strip('0,1,6,4'))

a='Pankaj'
print(a.isalpha())
b='Pankaj live in Kharar'
print(b.isalpha())

a='8988440386'
print(a.isdigit())
b='Pankaj'
print(b.isdigit())

a='Pankaj Chauhan Baginta'
print(a.startswith('Pankaj'))
print(a.startswith('Chauhan',4,5))
print(a.startswith('Pankaj',223,123))

a='Pankaj Chauhan Baginta'
b='Baginta'
print(a.endswith(b))

a="pankaj chuahan baginta"
b="ta"
print(a.find(b))

a="Pankaj Chauhan"
print(a.replace('Chauhan','Singh'))

a='pankaj chauhan baginta'
print(a.split())

a='pankaj chauhan baginta'
b='-'
print(b.join(a))